import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";

export interface RealDeal {
  id: string;
  deal_name: string;
  deal_number: string;
  deal_value: number;
  escrow_amount: number | null;
  closing_date: string | null;
  status: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  seed_key: string | null;
}

const TEMPLATE_CONDITIONS = [
  "Regulatory Approval Received",
  "Board Resolution Approved",
  "All KYC/KYB Verified",
  "Docs Executed",
  "Escrow Funded",
];

const TEMPLATE_CAP_TABLE = [
  { shareholder_name: "Founder A", ownership_pct: 30, payout_amount: 0 },
  { shareholder_name: "Founder B", ownership_pct: 20, payout_amount: 0 },
  { shareholder_name: "Series A Investor", ownership_pct: 15, payout_amount: 0 },
  { shareholder_name: "Series B Investor", ownership_pct: 10, payout_amount: 0 },
  { shareholder_name: "Employee Option Pool", ownership_pct: 7, payout_amount: 0 },
  { shareholder_name: "Other Investors", ownership_pct: 18, payout_amount: 0 },
];

export function useDealOperations() {
  const { user } = useAuth();
  const { toast } = useToast();

  const createDeal = async (params: {
    deal_name: string;
    deal_value: number;
    closing_date?: string | null;
    escrow_amount?: number;
  }): Promise<RealDeal | null> => {
    if (!user) {
      toast({ title: "Authentication required", variant: "destructive" });
      return null;
    }

    const { data, error } = await supabase
      .from("deals")
      .insert({
        deal_name: params.deal_name,
        deal_value: params.deal_value,
        closing_date: params.closing_date || null,
        escrow_amount: params.escrow_amount || 0,
        created_by: user.id,
        status: "draft",
        deal_number: "", // auto-generated by trigger
      })
      .select()
      .single();

    if (error) {
      toast({ title: "Error creating deal", description: error.message, variant: "destructive" });
      return null;
    }

    // Add creator as participant
    await supabase.from("deal_participants").insert({
      deal_id: data.id,
      user_id: user.id,
      party_role: "admin",
    });

    // Create deal settings
    await supabase.from("deal_settings").insert({
      deal_id: data.id,
    });

    return data as RealDeal;
  };

  const createDealFromTemplate = async (): Promise<RealDeal | null> => {
    const deal = await createDeal({
      deal_name: "New Template Deal",
      deal_value: 50_000_000,
      closing_date: new Date(Date.now() + 90 * 86400000).toISOString().split("T")[0],
      escrow_amount: 5_000_000,
    });

    if (!deal) return null;

    // Seed conditions
    const conditionRows = TEMPLATE_CONDITIONS.map((title) => ({
      deal_id: deal.id,
      title,
      status: "NOT_STARTED" as const,
    }));
    await supabase.from("conditions").insert(conditionRows);

    // Seed cap table
    const capRows = TEMPLATE_CAP_TABLE.map((entry) => ({
      deal_id: deal.id,
      shareholder_name: entry.shareholder_name,
      ownership_pct: entry.ownership_pct,
      payout_amount: Math.round(deal.deal_value * entry.ownership_pct / 100),
    }));
    await supabase.from("cap_table_entries").insert(capRows);

    // Audit log
    await supabase.from("audit_log").insert({
      deal_id: deal.id,
      user_id: user!.id,
      action: "DEAL_CREATED_FROM_TEMPLATE",
      details: { template: "default", deal_name: deal.deal_name },
    });

    toast({ title: "Deal created from template" });
    return deal;
  };

  const fetchDeals = async (): Promise<RealDeal[]> => {
    const { data } = await supabase
      .from("deals")
      .select("*")
      .order("created_at", { ascending: false });
    return (data as RealDeal[]) || [];
  };

  const fetchDeal = async (id: string): Promise<RealDeal | null> => {
    const { data } = await supabase
      .from("deals")
      .select("*")
      .eq("id", id)
      .single();
    return data as RealDeal | null;
  };

  return { createDeal, createDealFromTemplate, fetchDeals, fetchDeal };
}
