import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";

export interface RealDeal {
  id: string;
  deal_name: string;
  deal_number: string;
  deal_value: number;
  escrow_amount: number | null;
  closing_date: string | null;
  status: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  seed_key: string | null;
  deal_kind?: string;
}

export interface DealTemplate {
  id: string;
  deal_name: string;
  seed_key: string | null;
}

export function useDealOperations() {
  const { user } = useAuth();
  const { toast } = useToast();

  const createDeal = async (params: {
    deal_name: string;
    deal_value: number;
    closing_date?: string | null;
    escrow_amount?: number;
    templateId?: string | null;
  }): Promise<RealDeal | null> => {
    const { data, error } = await supabase
      .from("deals")
      .insert({
        deal_name: params.deal_name,
        deal_value: params.deal_value,
        closing_date: params.closing_date || null,
        escrow_amount: params.escrow_amount || 0,
        created_by: user?.id || null,
        status: "draft",
        deal_number: "", // auto-generated by trigger
        deal_kind: "live" as any,
      })
      .select()
      .single();

    if (error) {
      toast({ title: "Error creating deal", description: error.message, variant: "destructive" });
      return null;
    }

    // Add creator as participant if authenticated
    if (user) {
      await supabase.from("deal_participants").insert({
        deal_id: data.id,
        user_id: user.id,
        party_role: "admin",
      });
    }

    // Create deal settings
    await supabase.from("deal_settings").insert({
      deal_id: data.id,
    });

    // Apply template: copy conditions from template deal
    if (params.templateId) {
      const { data: templateConditions } = await supabase
        .from("conditions")
        .select("title")
        .eq("deal_id", params.templateId);

      if (templateConditions && templateConditions.length > 0) {
        const conditionRows = templateConditions.map((c: any) => ({
          deal_id: data.id,
          title: c.title,
          status: "NOT_STARTED" as any,
        }));
        await supabase.from("conditions").insert(conditionRows as any);
      }
    }

    return data as RealDeal;
  };

  const fetchTemplates = async (): Promise<DealTemplate[]> => {
    const { data } = await (supabase
      .from("deals")
      .select("id, deal_name, seed_key") as any)
      .eq("deal_kind", "template")
      .order("deal_name");
    return (data as DealTemplate[]) || [];
  };

  const fetchDeals = async (): Promise<RealDeal[]> => {
    const { data } = await (supabase
      .from("deals")
      .select("*") as any)
      .in("deal_kind", ["demo", "live"])
      .order("created_at", { ascending: false });
    return (data as RealDeal[]) || [];
  };

  const fetchDeal = async (id: string): Promise<RealDeal | null> => {
    const { data } = await supabase
      .from("deals")
      .select("*")
      .eq("id", id)
      .single();
    return data as RealDeal | null;
  };

  return { createDeal, fetchTemplates, fetchDeals, fetchDeal };
}
