import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";

export interface RealDeal {
  id: string;
  deal_name: string;
  deal_number: string;
  deal_value: number;
  escrow_amount: number | null;
  closing_date: string | null;
  status: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  seed_key: string | null;
  deal_kind?: string;
  template_blueprint?: any;
  owner_id?: string | null;
  visibility?: string;
  is_demo?: boolean;
  buyer?: string | null;
  seller?: string | null;
  target_company?: string | null;
  sector?: string | null;
  deal_type?: string | null;
  currency?: string | null;
  jurisdiction?: string | null;
}

export interface DealSummaryCounts {
  deal_id: string;
  partiesCount: number;
  docsCount: number;
  capTableCount: number;
  waterfallTiers: number;
  conditionsMet: number;
  conditionsTotal: number;
  approvalsGranted: number;
  approvalsTotal: number;
}

export interface DealTemplate {
  id: string;
  deal_name: string;
  seed_key: string | null;
}

export function useDealOperations() {
  const { user } = useAuth();
  const { toast } = useToast();

  const createDeal = async (params: {
    deal_name: string;
    deal_value: number;
    closing_date?: string | null;
    escrow_amount?: number;
    templateId?: string | null;
    buyer?: string | null;
    seller?: string | null;
    target_company?: string | null;
    sector?: string | null;
    deal_type?: string | null;
    currency?: string | null;
    jurisdiction?: string | null;
    signing_date?: string | null;
    /** When the caller knows the active workspace (multi-tenancy), inject it
     *  so the deal lands in the right org. Optional for pre-deploy fallback. */
    org_id?: string | null;
  }): Promise<RealDeal | null> => {
    // Defense in depth — the deals RLS policy requires owner_id = auth.uid().
    // Without a signed-in user we'd get "new row violates row-level security
    // policy for table deals", which is unreadable. Fail fast with a humane
    // toast instead.
    if (!user?.id) {
      toast({
        title: "Sign in to create a deal",
        description: "Your session has expired or you're not signed in. Sign in again and try again.",
        variant: "destructive",
      });
      return null;
    }
    const { data, error } = await supabase
      .from("deals")
      .insert({
        deal_name: params.deal_name,
        deal_value: params.deal_value,
        closing_date: params.closing_date || null,
        escrow_amount: params.escrow_amount || 0,
        created_by: user?.id || null,
        status: "draft",
        deal_number: "", // auto-generated by trigger
        deal_kind: "live" as any,
        owner_id: user?.id || null,
        visibility: "private",
        is_demo: false,
        buyer: params.buyer || null,
        seller: params.seller || null,
        target_company: params.target_company || null,
        sector: params.sector || null,
        deal_type: params.deal_type || null,
        currency: params.currency || 'USD',
        jurisdiction: params.jurisdiction || null,
        signing_date: params.signing_date || null,
        // org_id is sent when multi-tenancy is live; ignored by the DB
        // (column nullable) when the schema isn't deployed yet.
        org_id: params.org_id || null,
      } as any)
      .select()
      .single();

    if (error) {
      toast({ title: "Error creating deal", description: error.message, variant: "destructive" });
      return null;
    }

    // Add creator as participant if authenticated
    if (user) {
      await supabase.from("deal_participants").insert({
        deal_id: data.id,
        user_id: user.id,
        party_role: "admin",
      });
    }

    // Create deal settings
    await supabase.from("deal_settings").insert({
      deal_id: data.id,
    });

    // Apply template: copy conditions + store blueprint metadata
    if (params.templateId) {
      const { data: templateConditions } = await supabase
        .from("conditions")
        .select("title")
        .eq("deal_id", params.templateId);

      if (templateConditions && templateConditions.length > 0) {
        const conditionRows = templateConditions.map((c: any) => ({
          deal_id: data.id,
          title: c.title,
          status: "NOT_STARTED" as any,
        }));
        await supabase.from("conditions").insert(conditionRows as any);
      }

      const { data: templateDeal } = await (supabase
        .from("deals")
        .select("template_blueprint") as any)
        .eq("id", params.templateId)
        .single();

      if (templateDeal?.template_blueprint) {
        await (supabase
          .from("deals")
          .update({ template_blueprint: templateDeal.template_blueprint } as any) as any)
          .eq("id", data.id);
      }
    }

    toast({ title: "Deal created", description: data.deal_name });
    return data as RealDeal;
  };

  const fetchTemplates = async (): Promise<DealTemplate[]> => {
    const { data } = await (supabase
      .from("deals")
      .select("id, deal_name, seed_key") as any)
      .eq("deal_kind", "template")
      .order("deal_name");
    return (data as DealTemplate[]) || [];
  };

  // Org-aware fetch:
  // - If orgId is given, scope to deals in that org. Demo deals come through
  //   when the active org IS the demo org (caller passes its id).
  // - If no orgId (defensive fallback when multi-tenancy schema isn't
  //   deployed or the user has no orgs yet), legacy behavior: filter by
  //   is_demo flag the way the app used to.
  const fetchDeals = async (options?: { includeDemo?: boolean; orgId?: string | null }): Promise<RealDeal[]> => {
    const includeDemo = options?.includeDemo ?? false;
    let query = (supabase.from("deals").select("*") as any)
      .neq("deal_kind", "template")
      .order("created_at", { ascending: false });

    if (options?.orgId) {
      // Multi-tenancy path: only deals in this org. Phase-1 RLS already
      // guarantees the user can only see their orgs' deals, so this is a
      // UX scoping filter, not a security boundary.
      query = query.eq("org_id", options.orgId);
    } else if (!includeDemo) {
      // Legacy fallback: hide demo deals from real-customer view.
      query = query.eq("is_demo", false);
    }

    const { data } = await query;
    return (data as RealDeal[]) || [];
  };

  const fetchDeal = async (id: string): Promise<RealDeal | null> => {
    const { data } = await supabase
      .from("deals")
      .select("*")
      .eq("id", id)
      .single();
    return data as RealDeal | null;
  };

  const duplicateDeal = async (dealId: string): Promise<RealDeal | null> => {
    const { data, error } = await supabase.functions.invoke("duplicate-deal", {
      body: { deal_id: dealId },
    });

    if (error) {
      toast({ title: "Error duplicating deal", description: error.message, variant: "destructive" });
      return null;
    }

    toast({ title: "Deal duplicated", description: `Created "${data.deal_name}"` });
    return data as RealDeal;
  };

  const fetchDealSummaries = async (dealIds: string[]): Promise<Record<string, DealSummaryCounts>> => {
    if (dealIds.length === 0) return {};

    // Query all canonical data sources — same tables used by workspace modules
    const [capEntries, contractDocs, dealDocs, dealParties, deals, tiers, conditions, approvals] = await Promise.all([
      supabase.from("cap_table_entries").select("deal_id, role, ownership_pct").in("deal_id", dealIds),
      supabase.from("contract_documents").select("deal_id, id").in("deal_id", dealIds),
      supabase.from("deal_documents").select("deal_id, id").in("deal_id", dealIds),
      supabase.from("deal_parties").select("deal_id, id").in("deal_id", dealIds),
      supabase.from("deals").select("id, buyer, seller, target_company").in("id", dealIds),
      supabase.from("waterfall_tiers").select("deal_id").in("deal_id", dealIds),
      supabase.from("conditions").select("deal_id, status").in("deal_id", dealIds),
      supabase.from("deal_approvals").select("deal_id, status").in("deal_id", dealIds),
    ]);

    const count = (rows: any[] | null, id: string) => (rows || []).filter((r: any) => r.deal_id === id).length;

    const result: Record<string, DealSummaryCounts> = {};
    for (const id of dealIds) {
      // Parties: deal_parties rows + inferred from deal fields (buyer/seller/target) + cap_table party-role entries
      const dpCount = count(dealParties.data, id);
      const dealRecord = (deals.data || []).find((d: any) => d.id === id);
      const inferredCount = [dealRecord?.buyer, dealRecord?.seller, dealRecord?.target_company].filter(Boolean).length;
      const capRows = (capEntries.data || []).filter((r: any) => r.deal_id === id);
      const partyRoleEntries = capRows.filter((r: any) =>
        ['Buyer', 'Seller', 'Target', 'Escrow Agent', 'Lender', 'Buyer Counsel', 'Seller Counsel', 'Paying Agent'].includes(r.role)
      );
      // Deduplicate: unique party count = deal_parties + inferred deal fields + cap_table party roles
      const totalParties = dpCount + inferredCount + partyRoleEntries.length;

      // Cap table: equity holders only (ownership > 0, non-party roles)
      const equityHolders = capRows.filter((r: any) =>
        Number(r.ownership_pct) > 0 &&
        !['Buyer', 'Seller', 'Target', 'Escrow Agent', 'Lender', 'Buyer Counsel', 'Seller Counsel', 'Paying Agent'].includes(r.role)
      );

      // Documents: union of contract_documents + deal_documents (deduplicated by id)
      const contractDocIds = new Set((contractDocs.data || []).filter((r: any) => r.deal_id === id).map((r: any) => r.id));
      const dealDocIds = new Set((dealDocs.data || []).filter((r: any) => r.deal_id === id).map((r: any) => r.id));
      const allDocIds = new Set([...contractDocIds, ...dealDocIds]);

      const condRows = (conditions.data || []).filter((r: any) => r.deal_id === id);
      const appRows = (approvals.data || []).filter((r: any) => r.deal_id === id);
      result[id] = {
        deal_id: id,
        partiesCount: totalParties,
        docsCount: allDocIds.size,
        capTableCount: equityHolders.length,
        waterfallTiers: count(tiers.data, id),
        conditionsMet: condRows.filter((c: any) => c.status === 'MET' || c.status === 'SATISFIED' || c.status === 'WAIVED').length,
        conditionsTotal: condRows.length,
        approvalsGranted: appRows.filter((a: any) => a.status === 'approved' || a.status === 'completed').length,
        approvalsTotal: appRows.length,
      };
    }
    return result;
  };

  const softDeleteDeal = async (dealId: string): Promise<boolean> => {
    if (!user) return false;

    const { error } = await supabase.rpc("soft_delete_deal", {
      _deal_id: dealId,
    });

    if (error) {
      const msg = error.message || "";
      if (msg.includes("demo")) {
        toast({ title: "Cannot delete demo deal", description: "Demo deals are read-only and can't be deleted.", variant: "destructive" });
      } else if (msg.includes("Permission")) {
        toast({ title: "Permission denied", description: "You can only delete deals you created.", variant: "destructive" });
      } else if (msg.includes("not found")) {
        toast({ title: "Deal not found", description: "This deal no longer exists.", variant: "destructive" });
      } else {
        toast({ title: "Error deleting deal", description: msg, variant: "destructive" });
      }
      return false;
    }

    toast({ title: "Deal deleted", description: "The deal has been removed from your workspace." });
    return true;
  };

  return { createDeal, fetchTemplates, fetchDeals, fetchDeal, fetchDealSummaries, duplicateDeal, softDeleteDeal };
}
