import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, BookOpen } from 'lucide-react';

const sections = [
  { title: '1. Purpose', content: 'This Acceptable Use Policy ("Policy") governs the use of the PIVT platform and services ("Services"). It is designed to ensure lawful, secure, and responsible use of the platform.' },
  { title: '2. Scope', content: 'This Policy applies to all users of PIVT, including individuals, organizations, and their representatives accessing the platform.' },
  { title: '3. Permitted Use', content: 'Users may use PIVT solely for legitimate business purposes related to transaction management, document processing, and financial workflow coordination.' },
  { title: '4. Prohibited Activities', content: 'Users may not:', bullets: ['Engage in illegal, fraudulent, or deceptive activities', 'Submit false or misleading financial or transaction data', 'Attempt to gain unauthorized access to systems or data', 'Interfere with or disrupt platform functionality', 'Use the platform to distribute malware or harmful code', 'Exploit the platform for unauthorized surveillance or data extraction'] },
  { title: '5. Financial Integrity', content: 'Users must ensure all financial and transaction-related data is accurate and verified. PIVT is not responsible for errors resulting from inaccurate or incomplete user inputs.' },
  { title: '6. AI Usage Restrictions', content: 'Outputs generated by Newton AI are for informational purposes only and must not be used as the sole basis for financial, legal, or compliance decisions without independent verification.' },
  { title: '7. Security Obligations', content: 'Users are responsible for maintaining the confidentiality of their credentials and ensuring that access to the platform is secure within their organization.' },
  { title: '8. Enforcement', content: 'PIVT reserves the right to:', bullets: ['Monitor usage for compliance', 'Suspend or terminate access for violations', 'Investigate suspected misuse', 'Report unlawful activities to authorities'] },
  { title: '9. Reporting Violations', content: 'If you become aware of misuse or violations of this Policy, please report it to:', afterNote: 'Email: security@pivttech.ai' },
  { title: '10. Updates', content: 'PIVT may update this Policy from time to time. Continued use of the Services constitutes acceptance of any updates.' },
  { title: '11. Contact', content: 'If you have any questions about this Policy, please contact:', afterNote: 'PIVT, Inc.\nEmail: legal@pivttech.ai' },
];

const AcceptableUsePage: React.FC = () => (
  <div className="min-h-screen bg-background">
    <div className="max-w-3xl mx-auto px-6 py-12">
      <Link to="/" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground mb-8 transition-colors">
        <ArrowLeft className="w-4 h-4" /> Back to PIVT
      </Link>

      <div className="flex items-start gap-4 mb-4">
        <div className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0" style={{ background: 'var(--pivt-gradient-primary)' }}>
          <BookOpen className="w-5 h-5 text-white" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-foreground tracking-tight">Acceptable Use Policy</h1>
          <p className="text-sm text-muted-foreground mt-0.5">PIVT, Inc. · Last updated: March 19, 2026</p>
        </div>
      </div>

      <p className="text-sm text-muted-foreground mb-4 ml-14">Guidelines for responsible and secure use of the PIVT platform.</p>

      <div className="mb-10 p-4 rounded-lg border border-border bg-muted/20">
        <p className="text-sm text-muted-foreground leading-relaxed">
          PIVT is designed for secure, professional transaction workflows. Misuse of the platform may result in suspension or termination.
        </p>
      </div>

      <div className="space-y-8">
        {sections.map((s) => (
          <section key={s.title}>
            <h2 className="text-lg font-semibold text-foreground mb-2">{s.title}</h2>
            <p className="text-sm leading-relaxed text-muted-foreground">{s.content}</p>
            {s.bullets && (
              <ul className="mt-2 space-y-1 list-disc pl-5 text-sm text-muted-foreground">
                {s.bullets.map((b) => <li key={b}>{b}</li>)}
              </ul>
            )}
            {s.afterNote && (
              <p className="mt-3 text-sm text-muted-foreground whitespace-pre-line">{s.afterNote}</p>
            )}
          </section>
        ))}
      </div>

      <div className="mt-16 pt-6 border-t border-border flex items-center gap-4 text-xs text-muted-foreground/60 flex-wrap">
        <Link to="/privacy" className="hover:text-foreground transition-colors">Privacy Policy</Link>
        <span>·</span>
        <Link to="/terms" className="hover:text-foreground transition-colors">Terms of Service</Link>
        <span>·</span>
        <Link to="/cookie-policy" className="hover:text-foreground transition-colors">Cookie Policy</Link>
      </div>
    </div>
  </div>
);

export default AcceptableUsePage;
