import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, FileText } from 'lucide-react';

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: 'By accessing or using the PIVT platform ("Services"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, you may not use the Services.',
  },
  {
    title: '2. Description of Services',
    content: 'PIVT provides a platform to facilitate transaction coordination, document processing, and AI-assisted workflows ("Newton"). The Services are provided for informational and operational purposes only.',
  },
  {
    title: '3. No Legal or Financial Advice',
    content: 'PIVT does not provide legal, financial, investment, or tax advice. Users are solely responsible for obtaining appropriate professional advice before making decisions based on platform outputs.',
  },
  {
    title: '4. AI Disclaimer',
    content: 'Outputs generated by Newton AI are for informational purposes only. They may contain errors or omissions and must be independently verified by users before reliance.',
  },
  {
    title: '5. User Responsibilities',
    content: 'Users agree to:',
    bullets: [
      'Provide accurate and complete information',
      'Maintain confidentiality of login credentials',
      'Use the platform in compliance with applicable laws',
      'Independently verify all transaction details',
    ],
  },
  {
    title: '6. Prohibited Conduct',
    content: 'Users may not:',
    bullets: [
      'Engage in fraudulent or illegal activity',
      'Attempt unauthorized access to the platform',
      'Interfere with system integrity or security',
      'Use the platform for harmful or abusive purposes',
    ],
  },
  {
    title: '7. Data Handling',
    content: 'Use of the platform is subject to the Privacy Policy. Users acknowledge that transaction and financial data may be processed to provide Services.',
  },
  {
    title: '8. Intellectual Property',
    content: 'All platform content, software, and technology are owned by PIVT, Inc. Users are granted a limited, non-exclusive license to use the Services.',
  },
  {
    title: '9. Limitation of Liability',
    content: 'To the fullest extent permitted by law, PIVT shall not be liable for any indirect, incidental, or consequential damages, including financial losses arising from use of the platform or reliance on outputs.',
  },
  {
    title: '10. Indemnification',
    content: 'Users agree to indemnify and hold harmless PIVT, Inc. from claims arising out of misuse of the platform or violation of these Terms.',
  },
  {
    title: '11. Termination',
    content: 'PIVT may suspend or terminate access at any time for violations, security risks, or legal requirements.',
  },
  {
    title: '12. Modifications',
    content: 'We may update these Terms from time to time. Continued use constitutes acceptance of updated Terms.',
  },
  {
    title: '13. Governing Law',
    content: 'These Terms are governed by the laws of the State of California, without regard to conflict of law principles.',
  },
  {
    title: '14. Contact',
    content: 'If you have any questions about these Terms, please contact:',
    afterNote: 'PIVT, Inc.\nEmail: legal@pivttech.ai',
  },
];

const TermsOfServicePage: React.FC = () => {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <Link to="/" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to PIVT
        </Link>

        <div className="flex items-start gap-4 mb-4">
          <div className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0" style={{ background: 'var(--pivt-gradient-primary)' }}>
            <FileText className="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-foreground tracking-tight">Terms of Service</h1>
            <p className="text-sm text-muted-foreground mt-0.5">PIVT, Inc. · Last updated: March 19, 2026</p>
          </div>
        </div>

        <div className="mb-10 p-4 rounded-lg border border-border bg-muted/20">
          <p className="text-sm text-muted-foreground leading-relaxed">
            PIVT provides secure infrastructure for transaction workflows. Users remain responsible for independent verification of all financial and legal information.
          </p>
        </div>

        <div className="space-y-8">
          {sections.map((section) => (
            <section key={section.title}>
              <h2 className="text-lg font-semibold text-foreground mb-2">{section.title}</h2>
              <p className="text-sm leading-relaxed text-muted-foreground">{section.content}</p>

              {section.bullets && (
                <ul className="mt-2 space-y-1 list-disc pl-5 text-sm text-muted-foreground">
                  {section.bullets.map((b) => (
                    <li key={b}>{b}</li>
                  ))}
                </ul>
              )}

              {section.afterNote && (
                <p className="mt-3 text-sm text-muted-foreground whitespace-pre-line">{section.afterNote}</p>
              )}
            </section>
          ))}
        </div>

        <div className="mt-16 pt-6 border-t border-border flex items-center gap-4 text-xs text-muted-foreground/60">
          <Link to="/privacy" className="hover:text-foreground transition-colors">Privacy Policy</Link>
          <span>·</span>
          <Link to="/cookie-policy" className="hover:text-foreground transition-colors">Cookie Policy</Link>
        </div>
      </div>
    </div>
  );
};

export default TermsOfServicePage;
