import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    // Get the user from the auth header
    const authHeader = req.headers.get("authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    // Verify caller
    const supabaseUser = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } },
    );
    const { data: { user }, error: authError } = await supabaseUser.auth.getUser();
    if (authError || !user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { deal_id } = await req.json();
    if (!deal_id) {
      return new Response(JSON.stringify({ error: "deal_id required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Fetch source deal
    const { data: source, error: srcErr } = await supabaseAdmin
      .from("deals")
      .select("*")
      .eq("id", deal_id)
      .single();

    if (srcErr || !source) {
      return new Response(JSON.stringify({ error: "Deal not found" }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Create new deal
    const { data: newDeal, error: createErr } = await supabaseAdmin
      .from("deals")
      .insert({
        deal_name: source.deal_name + " (My copy)",
        deal_value: source.deal_value,
        escrow_amount: source.escrow_amount,
        closing_date: source.closing_date,
        status: "draft",
        deal_number: "", // auto-generated by trigger
        deal_kind: "live",
        owner_id: user.id,
        created_by: user.id,
        visibility: "private",
        is_demo: false,
        template_blueprint: source.template_blueprint,
      })
      .select()
      .single();

    if (createErr || !newDeal) {
      return new Response(JSON.stringify({ error: createErr?.message || "Failed to create deal" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const newId = newDeal.id;

    // Add user as participant
    await supabaseAdmin.from("deal_participants").insert({
      deal_id: newId, user_id: user.id, party_role: "admin",
    });

    // Create deal settings
    await supabaseAdmin.from("deal_settings").insert({ deal_id: newId });

    // Helper to copy rows from a child table
    const copyTable = async (
      table: string,
      selectCols: string,
      transform: (row: any) => any,
    ) => {
      const { data: rows } = await supabaseAdmin
        .from(table)
        .select(selectCols)
        .eq("deal_id", deal_id);
      if (rows && rows.length > 0) {
        const mapped = rows.map(transform);
        await supabaseAdmin.from(table).insert(mapped);
      }
    };

    // Copy conditions
    await copyTable("conditions", "title, status", (r: any) => ({
      deal_id: newId, title: r.title, status: r.status,
    }));

    // Copy cap_table_entries
    await copyTable("cap_table_entries", "shareholder_name, ownership_pct, payout_amount, escrow_holdback, fees, net_payout", (r: any) => ({
      deal_id: newId, shareholder_name: r.shareholder_name, ownership_pct: r.ownership_pct,
      payout_amount: r.payout_amount, escrow_holdback: r.escrow_holdback, fees: r.fees, net_payout: r.net_payout,
    }));

    // Copy contract_documents (metadata only, not files)
    await copyTable("contract_documents", "filename, doc_type, status, text_content", (r: any) => ({
      deal_id: newId, filename: r.filename, doc_type: r.doc_type, status: r.status,
      text_content: r.text_content, uploaded_by: user.id,
    }));

    // Copy waterfall_tiers
    await copyTable("waterfall_tiers", "name, tier_rank, allocation_logic_type, params", (r: any) => ({
      deal_id: newId, name: r.name, tier_rank: r.tier_rank,
      allocation_logic_type: r.allocation_logic_type, params: r.params,
    }));

    // Copy payment_instructions
    await copyTable("payment_instructions", "title, amount, currency, status", (r: any) => ({
      deal_id: newId, title: r.title, amount: r.amount, currency: r.currency, status: "DRAFT",
    }));

    // Copy ontology_documents
    await copyTable("ontology_documents", "title, doc_type, url", (r: any) => ({
      deal_id: newId, title: r.title, doc_type: r.doc_type, url: r.url,
    }));

    // Copy ontology_approvals
    await copyTable("ontology_approvals", "approval_type, status", (r: any) => ({
      deal_id: newId, approval_type: r.approval_type, status: "PENDING",
    }));

    return new Response(JSON.stringify({ id: newId, deal_name: newDeal.deal_name }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: (err as Error).message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
